import { Twitch } from "lucide-react";

export const candidatos = [
    {
        nombre: 'Nombre del candidato',
        partido: 'MC',
        color_partido: '#FFA500',
        comunidad: 222000,
        aumento_comunidad: 27,
        interacciones: 127000,
        aumento_interacciones: 39,
        publicaciones: 675,
        aumento_publicaciones: -15,
        facebook: 'https://facebook.com/candidato',
        twitter: 'https://twitter.com/candidato',
        instagram: 'https://instagram.com/candidato',
        linkedin: 'https://linkedin.com/candidato',
        youtube: 'https://youtube.com/candidato',
        tiktok: 'https://tiktok.com/candidato',
        whatsapp: 'https://whatsapp.com/candidato',
        seguidores_nuevos: 689,
        interacciones_nuevas: 542,
        menciones_nuevas: 723,
        edad_votantes: 43,
        porcentaje_hombres: 67,
        aumento_intencion: 35,
        redes_mas_usadas: ['Facebook', 'Instagram', 'Twitter'],
        hashtags: ['#Candidato2024', '#MC', '#Elecciones2024'],
    },
    {
        nombre: 'Nombre del candidato',
        partido: 'Morena',
        color_partido: 'red',
        comunidad: 317000,
        aumento_comunidad: 12,
        interacciones: 254000,
        aumento_interacciones: 17,
        publicaciones: 1874,
        aumento_publicaciones: -87,
        facebook: 'https://facebook.com/candidato',
        twitter: 'https://twitter.com/candidato',
        instagram: 'https://instagram.com/candidato',
        linkedin: 'https://linkedin.com/candidato',
        youtube: 'https://youtube.com/candidato',
        tiktok: 'https://tiktok.com/candidato',
        seguidores_nuevos: 1289,
        interacciones_nuevas: 342,
        menciones_nuevas: 123,
        edad_votantes: 46,
        porcentaje_hombres: 48,
        aumento_intencion: 33,
        redes_mas_usadas: ['Facebook', 'Instagram', 'Tiktok'],
        hashtags: ['#Candidato2024', '#Morena', '#Seguridad'],
    },
    {
        nombre: 'Nombre del candidato',
        partido: 'PAN',
        color_partido: '#0000FF',
        comunidad: 87000,
        aumento_comunidad: 7,
        interacciones: 14000,
        aumento_interacciones: -8,
        publicaciones: 275,
        aumento_publicaciones: 10,
        redes_sociales: ['Facebook', 'Twitter', 'Instagram'],
        facebook: 'https://facebook.com/candidato',
        twitter: 'https://twitter.com/candidato',
        instagram: 'https://instagram.com/candidato',
        linkedin: null,
        youtube: null,
        tiktok: null,
        seguidores_nuevos: 689,
        interacciones_nuevas: 542,
        menciones_nuevas: 723,
        edad_votantes: 43,
        porcentaje_hombres: 67,
        aumento_intencion: 35,
        redes_mas_usadas: ['Facebook', 'Twitter', 'Instagram'],
        hashtags: ['#PorMasEscuelas', '#PAN', '#Elecciones2024'],
    },
    {
        nombre: 'Nombre del candidato',
        partido: 'MC',
        color_partido: '#FFA500',
        comunidad: 528000,
        aumento_comunidad: 47,
        interacciones: 314000,
        aumento_interacciones: 25,
        publicaciones: 2146,
        aumento_publicaciones: 38,
        facebook: 'https://facebook.com/candidato',
        twitter: 'https://twitter.com/candidato',
        instagram: 'https://instagram.com/candidato',
        linkedin: 'https://linkedin.com/candidato',
        youtube: 'https://youtube.com/candidato',
        tiktok: 'https://tiktok.com/candidato',
        seguidores_nuevos: 8957,
        interacciones_nuevas: 7842,
        menciones_nuevas: 415,
        edad_votantes: 37,
        porcentaje_hombres: 58,
        aumento_intencion: 12,
        redes_mas_usadas: ['Tiktok', 'Instagram', 'Facebook'],
        hashtags: ['#ComunidadMC', '#MC', '#JaliscoUnido'],
    },
    {
        nombre: 'Nombre del candidato',
        partido: 'Verde',
        color_partido: '#008000',
        comunidad: 317000,
        aumento_comunidad: 12,
        interacciones: 87000,
        aumento_interacciones: 9,
        publicaciones: 412,
        aumento_publicaciones: -38,
        redes_sociales: ['Facebook', 'Instagram', 'Youtube', 'Tiktok'],
        facebook: 'https://facebook.com/candidato',
        twitter: null,
        instagram: 'https://instagram.com/candidato',
        linkedin: null,
        youtube: 'https://youtube.com/candidato',
        tiktok: 'https://tiktok.com/candidato',
        seguidores_nuevos: 189,
        interacciones_nuevas: 42,
        menciones_nuevas: 293,
        edad_votantes: 39,
        porcentaje_hombres: 52,
        aumento_intencion: -8,
        redes_mas_usadas: ['Instagram', 'Tiktok', 'Facebook'],
        hashtags: ['#MéxicoVerde', '#MejorarLaSalud', '#Educación'],
    },
]